apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: binding-{username}
  namespace: mc-{username}
subjects:
- kind: ServiceAccount
  name: {username}
  namespace: mc-{username}
roleRef:
  kind: Role
  name: minecraft-manager
  apiGroup: rbac.authorization.k8s.io