apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: mc-{username}
  name: minecraft-manager
rules:
# Core API group
- apiGroups: [""]
  resources: ["persistentvolumeclaims", "services"]
  verbs: ["create", "delete", "get", "list"]

# Pods (Since StatefulSet manages them)
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list"]

# Pod logs
- apiGroups: [""]
  resources: ["pods/log"]
  verbs: ["get"]

# Apps API group
- apiGroups: ["apps"]
  resources: ["statefulsets"]
  verbs: ["create", "delete", "get", "list", "patch"]