apiVersion: v1
kind: Service
metadata:
  name: {servername}
  namespace: mc-{username}
  labels:
    app: kubecraft
    server: {servername}
spec:
  ports:
  - port: 25565
    targetPort: 25565
    protocol: TCP
    name: minecraft
  type: NodePort
  selector:
    app: minecraft
    server: {servername}