apiVersion: v1
kind: Service
metadata:
  name: registration-service
  namespace: kubecraft-system
  labels:
    app: kubecraft
    component: registration
spec:
  type: NodePort
  selector:
    app: kubecraft
    component: registration
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30099
    protocol: TCP