apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kc-registration-admin-binding
  labels:
    app: kubecraft
    component: registration
subjects:
- kind: ServiceAccount
  name: registration-service
  namespace: kubecraft-system
roleRef:
  kind: ClusterRole
  name: kc-registration-admin
  apiGroup: rbac.authorization.k8s.io