apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kc-users-capacity-check
  labels:
    app: kubecraft
    component: rbac
  annotations:
    description: "Binds the clusterrole to multiple users"
subjects: []
roleRef:
  kind: ClusterRole
  name: kc-capacity-checker
  apiGroup: rbac.authorization.k8s.io