apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata: 
  name: kc-capacity-checker
  labels:
    app: kubecraft
    component: rbac
  annotations:
    description: "Read only permissions for pre-flight capacity checks. Allows users to check cluster memory and port availability"
rules:
- apiGroups: [""]
  resources: ["namespaces", "services", "pods"]
  verbs: ["get", "list"]